export enum routes {
  Home = "/",
  Services = "/services",
  Industries = "/industries",
  CaseStudy = "/case-study",
  About = "/about",
  EndToEndApplicationDevelopment = `${Services}/end-to-end-application-development`,
  ArtificialIntelligence = `${Services}/artificial-intelligence`,
  DemoVersion = `${Services}/demo-version`,
  RequirementAnalysisAndDevelopmentPlanning = `${Services}/requirement-analysis-and-development-planning`,
  AgileMethodologies = `${Services}/agile-methodologies`,
  OptimizeBusinessProcessesWithCRM = `${Services}/optimize-business-processes-with-crm`,
  CloudIntegration = `${Services}/cloud-integration`,
  FintechСaseStudy = `${CaseStudy}/fintech`,
}
