export enum routes {
  Home = "/",
  Services = "/services",
  Industries = "/industries",
  CaseStudy = "/case-studies",
  About = "/about",
  EndToEndApplicationDevelopment = `${Services}/end-to-end-application-development`,
  ArtificialIntelligence = `${Services}/artificial-intelligence`,
  DemoVersion = `${Services}/demo-version`,
  RequirementAnalysisAndDevelopmentPlanning = `${Services}/requirement-analysis-and-development-planning`,
  AgileMethodologies = `${Services}/agile-methodologies`,
  OptimizeBusinessProcessesWithCRM = `${Services}/optimize-business-processes-with-crm`,
  CloudIntegration = `${Services}/cloud-integration`,
  FintechСaseStudy = `${CaseStudy}/fintech-combination`,
  CryptoCaseStudy = `${CaseStudy}/advancing-crypto-innovation`,
  MediaResearchCaseStudy = `${CaseStudy}/optimizing-media-research`,
  PharmaceuticalDistributionCaseStudy = `${CaseStudy}/pharmaceutical-distribution`,
  TransformingECommerceCaseStudy = `${CaseStudy}/transforming-e-commerce`,
  RevolutionInTelecommunicationsCaseStudy = `${CaseStudy}/revolution-in-telecommunications`,
}
